USE [master]
GO

/****** Object:  Database [E-LEARNING]    Script Date: 01/12/2019 01:16:59 p. m. ******/
CREATE DATABASE [E-LEARNING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'E-LEARNING', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL\MSSQL\DATA\E-LEARNING.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'E-LEARNING_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL\MSSQL\DATA\E-LEARNING_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [E-LEARNING] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [E-LEARNING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [E-LEARNING] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [E-LEARNING] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [E-LEARNING] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [E-LEARNING] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [E-LEARNING] SET ARITHABORT OFF 
GO

ALTER DATABASE [E-LEARNING] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [E-LEARNING] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [E-LEARNING] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [E-LEARNING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [E-LEARNING] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [E-LEARNING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [E-LEARNING] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [E-LEARNING] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [E-LEARNING] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [E-LEARNING] SET  DISABLE_BROKER 
GO

ALTER DATABASE [E-LEARNING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [E-LEARNING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [E-LEARNING] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [E-LEARNING] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [E-LEARNING] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [E-LEARNING] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [E-LEARNING] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [E-LEARNING] SET RECOVERY FULL 
GO

ALTER DATABASE [E-LEARNING] SET  MULTI_USER 
GO

ALTER DATABASE [E-LEARNING] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [E-LEARNING] SET DB_CHAINING OFF 
GO

ALTER DATABASE [E-LEARNING] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [E-LEARNING] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [E-LEARNING] SET  READ_WRITE 
GO


